//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotonFramework.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Framework : global::System.Configuration.ApplicationSettingsBase {
        
        private static Framework defaultInstance = ((Framework)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Framework())));
        
        public static Framework Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4530")]
        public int MasterServerTCPPort {
            get {
                return ((int)(this["MasterServerTCPPort"]));
            }
            set {
                this["MasterServerTCPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5055")]
        public int ClientUDPPort {
            get {
                return ((int)(this["ClientUDPPort"]));
            }
            set {
                this["ClientUDPPort"] = value;
            }
        }
    }
}
